const courses = [
  {
    id: 0,
    studentType: "Undergraduate",
    title: "Bioinformatic Stats II",
    description: "Advanced analysis of biological data.",
    progress: 35,
    image: "/img/Circulatory-system.svg",
    imageBg: "red.300",
    status: "previous",
  },
  {
    id: 1,
    studentType: "Graduate",
    title: "Intro to Biotech Lab",
    description: "Introduction to laboratory techniques in biotechnology.",
    progress: 25,
    image: "/img/Biologist-2.svg",
    imageBg: "blue.300",
    status: "current",
  },
  {
    id: 2,
    studentType: "Graduate",
    title: "Cellular Biology I",
    description: "Study of the structure and function of cells.",
    progress: 78,
    image: "/img/Biologist-1.svg",
    imageBg: "yellow.300",
    status: "current",
  },
  {
    id: 3,
    studentType: "Graduate",
    title: "Techniques in MRNA Research",
    description: "Methods for studying messenger RNA molecules.",
    progress: 35,
    image: "/img/EarthandMoon.svg",
    imageBg: "teal.300",
    status: "future",
  },
  {
    id: 4,
    studentType: "Undergraduate",
    title: "Retroviruses IV",
    description: "Advanced study of retroviruses and their biology.",
    progress: 55,
    image: "/img/Retroviruses.svg",
    imageBg: "orange.300",
    status: "future",
  },
  {
    id: 5,
    studentType: "Undergraduate",
    title: "Retroviruses II",
    description: "Introduction to the study of retroviruses.",
    progress: 24,
    image: "/img/Retroviruses-2.svg",
    imageBg: "blue.300",
    status: "future",
  },
  {
    id: 6,
    studentType: "Graduate",
    title: "Stem Cell Lab",
    description: "Hands-on laboratory work with stem cells.",
    progress: 58,
    image: "/img/Stem-cell.svg",
    imageBg: "green.300",
    status: "previous",
  },
];

export default courses;
